sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[笔记](/notes/)'
    more: '[更多](/more/)'
        
social_links:
  github: http://github.com/tsl1997
  mail: mailto:xs@btcabc.cn
